services:
  mysql-shoplive:
    image: ${DOCKER_MYSQL_IMAGE}
    container_name: mysql-shoplive
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${LOCAL_USER}
      MYSQL_PASSWORD: ${LOCAL_PASS}
    ports:
      - "${OLD_ECOM_PORT}:3306"
    volumes:
      - old_ecom_data:/var/lib/mysql
    restart: unless-stopped
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password --sql-mode=${MYSQL_SQL_MODE}
    networks:
      - shoplive
      - ecommerce

  mysql-cross-prod:
    image: ${DOCKER_MYSQL_IMAGE}
    container_name: mysql-cross-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${LOCAL_USER}
      MYSQL_PASSWORD: ${LOCAL_PASS}
    ports:
      - "${CROSS_PROD_PORT}:3306"
    volumes:
      - cross_prod_data:/var/lib/mysql
    restart: unless-stopped
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password --sql-mode=${MYSQL_SQL_MODE}
    networks:
      - shoplive
      - ecommerce

networks:
  shoplive:
    external: true
  ecommerce:
    external: true

volumes:
  old_ecom_data:
  cross_prod_data:
